### ISSUE TITLE
trouble baking out BuildableDetailView pages

### ISSUE THREAD

**Issue by ryanvmenezes** [datadesk/django-bakery#76]
For a small personal project I think I've configured BuildableListViews properly (I can see the baked-out files) but I'm having issues with a BuildableDetailView that is supposed to bake out 10 profile pages. It works on my local server but this is the error I get when I try to run `python manage.py build`:

```python
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/ryan/.virtualenvs/cutthecheck/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/home/ryan/.virtualenvs/cutthecheck/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ryan/.virtualenvs/cutthecheck/local/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ryan/.virtualenvs/cutthecheck/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/home/ryan/.virtualenvs/cutthecheck/local/lib/python2.7/site-packages/bakery/management/commands/build.py", line 81, in handle
    self.build_views()
  File "/home/ryan/.virtualenvs/cutthecheck/local/lib/python2.7/site-packages/bakery/management/commands/build.py", line 188, in build_views
    view().build_method()
  File "/home/ryan/repos/cutthecheck/rosters/views.py", line 40, in build_queryset
    self.build_object(o)
  File "/home/ryan/.virtualenvs/cutthecheck/local/lib/python2.7/site-packages/bakery/views.py", line 196, in build_object
    self.request = RequestFactory().get(self.get_url(obj))
  File "/home/ryan/.virtualenvs/cutthecheck/local/lib/python2.7/site-packages/django/test/client.py", line 303, in get
    return self.generic('GET', path, secure=secure, **r)
  File "/home/ryan/.virtualenvs/cutthecheck/local/lib/python2.7/site-packages/django/test/client.py", line 357, in generic
    parsed = urlparse(path)
  File "/usr/lib/python2.7/urlparse.py", line 143, in urlparse
    tuple = urlsplit(url, scheme, allow_fragments)
  File "/usr/lib/python2.7/urlparse.py", line 182, in urlsplit
    i = url.find(':')
AttributeError: 'NoneType' object has no attribute 'find'
```

I can't figure out whether this is because of an improper setting or something in my view. Here is my [view](https://github.com/ryanvmenezes/cutthecheck/blob/master/rosters/views.py#L25-L40), [url](https://github.com/ryanvmenezes/cutthecheck/blob/master/cutthecheck/urls.py#L25-L29) and [settings.py](https://github.com/ryanvmenezes/cutthecheck/blob/master/cutthecheck/settings.py). Thanks

**Comment by palewire** [comment]
Looks like it doesn't like the "url" or output path configured on your view. How is that set?

**Comment by ryanvmenezes** [comment]
@palewire what do you mean by "output path" on my view?

**Comment by palewire** [comment]
[This stuff](http://django-bakery.readthedocs.org/en/latest/buildableviews.html#BuildableDetailView.get_build_path)

**Comment by ryanvmenezes** [comment]
Aha! I added get_url and get_build_path functions and it now works. Thanks.

**Comment by palewire** [comment]
Good. If you have ``get_absolute_url`` set on your model it will probably
solve itself without any configuration, FWIW.
