### ISSUE TITLE
Dynamic Filtering and BuildableListView

### ISSUE THREAD

**Issue by stvkas** [datadesk/django-bakery#99]
Does `BuildableListView` support [dynamic filtering](https://docs.djangoproject.com/en/dev/topics/class-based-views/generic-display/#dynamic-filtering)? I got this error on my project at work that uses django-bakery, and I was able to recreate it in the example project in a [branch on my fork](https://github.com/stvkas/django-bakery/tree/dynamic-filtering).

```
$ ./manage.py build
Traceback (most recent call last):
  File "./manage.py", line 9, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/stephen.kasica/Code/django-bakery/venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/Users/stephen.kasica/Code/django-bakery/venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/stephen.kasica/Code/django-bakery/venv/lib/python2.7/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/stephen.kasica/Code/django-bakery/venv/lib/python2.7/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/Users/stephen.kasica/Code/django-bakery/venv/lib/python2.7/site-packages/django_bakery-0.8.14-py2.7.egg/bakery/management/commands/build.py", line 76, in handle
    self.build_views()
  File "/Users/stephen.kasica/Code/django-bakery/venv/lib/python2.7/site-packages/django_bakery-0.8.14-py2.7.egg/bakery/management/commands/build.py", line 185, in build_views
    view().build_method()
  File "/Users/stephen.kasica/Code/django-bakery/venv/lib/python2.7/site-packages/django_bakery-0.8.14-py2.7.egg/bakery/views/list.py", line 44, in build_queryset
    self.build_file(path, self.get_content())
  File "/Users/stephen.kasica/Code/django-bakery/venv/lib/python2.7/site-packages/django_bakery-0.8.14-py2.7.egg/bakery/views/base.py", line 40, in get_content
    return self.get(self.request).render().content
  File "/Users/stephen.kasica/Code/django-bakery/venv/lib/python2.7/site-packages/django/views/generic/list.py", line 159, in get
    self.object_list = self.get_queryset()
  File "/Users/stephen.kasica/Code/django-bakery/django-bakery/example/date_views/views.py", line 43, in get_queryset
    self.reporter = get_object_or_404(Reporter, pk=self.kwargs.get('reporter'))
AttributeError: 'MyReporterListView' object has no attribute 'kwargs'
```

If this is a bug or a worthy enhancement, I can use some work hours towards it and make a pull request.

**Comment by palewire** [comment]
This should definitely be possible.

Though I'm not sure self.kwargs is set at that point when a ListView is run. Bakery isn't doing a ton to override the default Django ListView, so I wonder if it's just something simple. 

The use case you're raising is a tricky one I've run into before. In one sense, you are creating a "DetailView" for the reporter with each reporter's article list in the context, rather than a ListView for the Article. I wonder if it all might shake out if you just switch to BuildableDetailView instead and do your query in the ``get_context_data`` method.

**Comment by stvkas** [comment]
I like that workaround, one related model's list view is the other model's detail view. I was able to do that to replicate that dynamic-filtering behavior. It's in the[ latest commit](https://github.com/stvkas/django-bakery/commit/8e66bbbdc69f64200e68a2f7e4ea31446a551e8d) on that dynamic-filtering branch. Thanks for the help.
